# Generated by Django 5.0.3 on 2024-06-11 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="lvl",
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(verbose_name="Количество Валюты"),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Хозяин кошелька",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кошелёк",
                "verbose_name_plural": "Кошельки",
                "ordering": ("-id",),
                "indexes": [models.Index(fields=["owner"], name="owner_idx")],
            },
        ),
    ]
