# Generated by Django 5.0.3 on 2024-06-11 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Имя станции")),
                (
                    "location",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Местоположение точки"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание станции")),
            ],
            options={
                "verbose_name": ("Игровая станция",),
                "verbose_name_plural": ("Игровые станции",),
                "ordering": ("-id",),
                "indexes": [models.Index(fields=["location"], name="location_idx")],
            },
        ),
        migrations.CreateModel(
            name="GameTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_score",
                    models.PositiveSmallIntegerField(
                        verbose_name="Максимальная награда"
                    ),
                ),
                ("question", models.TextField(verbose_name="Вопрос задания")),
                (
                    "game_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="belonging_to",
                        to="quests.gamestage",
                        verbose_name="Игровая станция",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Игровое задание",),
                "verbose_name_plural": ("Игровые задания",),
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Matches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(null=True, verbose_name="Статус")),
                (
                    "game_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="played_at",
                        to="quests.gamestage",
                        verbose_name="Игровая станция",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="played_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Игрок",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Игровой матч",),
                "verbose_name_plural": ("Игровые матчи",),
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="MatchesTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        null=True, verbose_name="Заработанная награда"
                    ),
                ),
                (
                    "game_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_of",
                        to="quests.matches",
                        verbose_name="Матч задания",
                    ),
                ),
                (
                    "game_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_of",
                        to="quests.gametask",
                        verbose_name="Матч задания",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Игровое задание",),
                "verbose_name_plural": ("Игровые задания",),
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Task1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_1", models.CharField(max_length=128, verbose_name="Ответ 1")),
                ("answer_2", models.CharField(max_length=128, verbose_name="Ответ 2")),
                ("answer_3", models.CharField(max_length=128, verbose_name="Ответ 3")),
                ("answer_4", models.CharField(max_length=128, verbose_name="Ответ 4")),
                (
                    "correct_answer",
                    models.PositiveSmallIntegerField(verbose_name="Правильный ответ"),
                ),
                (
                    "game_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_category_of",
                        to="quests.gametask",
                        verbose_name="Игровое задание",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Задание 1-го типа",),
                "verbose_name_plural": ("Задания 1-го типа",),
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Task2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(max_length=128, verbose_name="Правильный ответ"),
                ),
                (
                    "radius",
                    models.PositiveSmallIntegerField(verbose_name="Интервал ответов"),
                ),
                (
                    "game_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_category_of",
                        to="quests.gametask",
                        verbose_name="Игровое задание",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Задание 2-го типа",),
                "verbose_name_plural": ("Задания 2-го типа",),
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Task3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture_1",
                    models.ImageField(
                        upload_to="quests/images/", verbose_name="Картинка 1"
                    ),
                ),
                (
                    "picture_2",
                    models.ImageField(
                        upload_to="quests/images/", verbose_name="Картинка 2"
                    ),
                ),
                (
                    "picture_3",
                    models.ImageField(
                        upload_to="quests/images/", verbose_name="Картинка 3"
                    ),
                ),
                (
                    "picture_4",
                    models.ImageField(
                        upload_to="quests/images/", verbose_name="Картинка 4"
                    ),
                ),
                (
                    "description_1",
                    models.CharField(max_length=512, verbose_name="Описание 1"),
                ),
                (
                    "description_2",
                    models.CharField(max_length=512, verbose_name="Описание 2"),
                ),
                (
                    "description_3",
                    models.CharField(max_length=512, verbose_name="Описание 3"),
                ),
                (
                    "description_4",
                    models.CharField(max_length=512, verbose_name="Описание 4"),
                ),
                (
                    "correct_answer",
                    models.PositiveSmallIntegerField(verbose_name="Правильный ответ"),
                ),
                (
                    "game_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="third_category_of",
                        to="quests.gametask",
                        verbose_name="Игровое задание",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Задание 3-го типа",),
                "verbose_name_plural": ("Задания 3-го типа",),
                "ordering": ("-id",),
            },
        ),
        migrations.AddIndex(
            model_name="gametask",
            index=models.Index(fields=["game_stage"], name="game_stage_idx"),
        ),
        migrations.AddIndex(
            model_name="matches",
            index=models.Index(fields=["user"], name="match_user_idx"),
        ),
        migrations.AddIndex(
            model_name="matchestask",
            index=models.Index(
                fields=["game_stage"], name="matches_task_game_stage_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task1",
            index=models.Index(fields=["game_task"], name="game_task1_idx"),
        ),
        migrations.AddIndex(
            model_name="task2",
            index=models.Index(fields=["game_task"], name="game_task2_idx"),
        ),
        migrations.AddIndex(
            model_name="task3",
            index=models.Index(fields=["game_task"], name="game_task3_idx"),
        ),
    ]
